First commit.
Mopgonpblr/Bookstore pull request #5
Opened 2024-11-16 11:44 UTC by Mopgonpblr

Using PostgreSQL, JDBC, Hikari. Decided not to jump high at first and added only the bookstore books constant table. Still don't know what to do with books lists in all the orders to fit them in a table.

Liquibase is connected as plugin in Maven and generates log files throw command line.

2024-11-17 08:05 UTC, Alexmansar commented
> Using PostgreSQL, JDBC, Hikari. Decided not to jump high at first and added only the bookstore books constant table. Still don't know what to do with books lists in all the orders to fit them in a table.
> 
> Liquibase is connected as plugin in Maven and generates log files throw command line.

You can also use Liquibase to add some kind of book at application startup.

2024-11-17 08:05 UTC, Alexmansar requested changes
@Mopgonpblr Hi)) I add some comments, please check them

2024-11-17 08:05 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/controller/Controller.java
> +    private static Properties properties;
why static?

2024-11-17 08:05 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/controller/DataControl.java
> +        String SQL_QUERY = "select * from library";
use like a constant. I mean on the class layer

2024-11-17 08:05 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/controller/HikariCPDataSource.java
> +    private static final Properties properties = Controller.getProperties();
if irs static filed, use UPPER_CASE

2024-11-18 09:47 UTC, Mopgonpblr commented
@Alexmansar I didn't find much about what I can do with Liquibase without using Spring/Hibernate.

2024-11-18 10:32 UTC, Alexmansar commented
@Mopgonpblr Chech ypur CI)

2024-11-18 10:33 UTC, Alexmansar requested changes
@Mopgonpblr And small question

2024-11-18 10:33 UTC, Alexmansar commented on src/main/resources/Data.txt
why txt not json?

2024-11-18 10:42 UTC, Mopgonpblr commented
> @Mopgonpblr Chech ypur CI)

@Alexmansar that's what I've been doing with test commits. It refuses to connect to my database even after I've changed postgresql.conf variable "listen_addresses" to "*"

2024-11-18 10:43 UTC, Mopgonpblr commented on src/main/resources/Data.txt
txt worked for me since we started working with data reading. I didn't feel the need to change it to JSON

2024-11-18 10:51 UTC, Alexmansar commented
> > @Mopgonpblr Chech ypur CI)
> 
> @Alexmansar that's what I've been doing with test commits. Git Action refuses to connect to my database even after I've changed postgresql.conf variable "listen_addresses" to "*". My local tests are successful

But why you need it?

2024-11-18 10:52 UTC, Alexmansar commented
DataControlTest your problem test
use mocks here, not real objects

2024-11-18 11:00 UTC, HKV203 commented
> DataControlTest your problem test use mocks here, not real objects

@Alexmansar  I guess it's late for me. 😅 
I found out that the reason was probably that I turned my Hikari data source into an object

2024-11-18 14:15 UTC, Alexmansar approved these changes
@Mopgonpblr Hi) please, merge it)

2024-11-18 14:44 UTC, merged