Spring, first try
Mopgonpblr/Bookstore pull request #7
Opened 2024-11-26 16:33 UTC by Mopgonpblr

It uses Spring Boot and shows the book list in the "Change Book Availability" part. 

It uses my own jpa starter now.

Still I don't really get what you meant about the second starter. I use Postgresql.

2024-11-26 18:10 UTC, Alexmansar requested changes
@Mopgonpblr Hi) please, fix some comments

2024-11-26 18:10 UTC, Alexmansar commented on pom.xml
> +        </dependency>
do we need it? we use boot,  so can use srarters

2024-11-26 18:10 UTC, Alexmansar commented on pom.xml
> +        </dependency>
also in our starters

2024-11-26 18:10 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/Main.java
> +    }
do we need it?

2024-11-26 18:10 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/Main.java
> +public class Main extends SpringBootServletInitializer {
extends SpringBootServletInitializer 
and this?

2024-11-26 18:10 UTC, Alexmansar commented on src/main/java/com/andersen/bookstore/controller/BookController.java
> +        }
this is service work

2024-11-26 19:08 UTC, Mopgonpblr commented on pom.xml
> +        </dependency>
@Alexmansar it isn't https://stackoverflow.com/questions/42154614/springboot-embedded-tomcat-and-tomcat-embed-jasper

2024-11-27 13:50 UTC, Alexmansar commented on pom.xml
> +        </dependency>
I general we don't need extra dependancy here) your sring boot already has it in spring-boot-starter-web
so just use spring-boot-starter-web to build your app)

2024-11-27 13:51 UTC, Alexmansar commented on pom.xml
> +        </dependency>
sp ypu ca just remove old solution with servlets ans tomcat, and use spring))

2024-11-27 13:55 UTC, Mopgonpblr commented on pom.xml
> +        </dependency>
@Alexmansar tomcat-jasper helps me to connect my Controller class and jsp files. If I take out this dependency, I get the error page instead of index.jsp and all the other pages my browser downloads with random names instead of opening

2024-11-27 13:57 UTC, HKV203 commented on pom.xml
> +        </dependency>
Even though I have spring-boot-starter-web in my dependencies

2024-11-27 14:00 UTC, Alexmansar commented on pom.xml
> +        </dependency>
Ok) you may be right)) jsp is not popular these days, and I've worked a long time ago)))

2024-11-27 14:00 UTC, Alexmansar approved these changes

2024-11-27 14:08 UTC, merged